/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedUFixedIdRouteImport } from './routes/_authenticated/u.$fixedId'
import { Route as AuthenticatedProfileSettingsRouteImport } from './routes/_authenticated/profile.settings'
import { Route as AuthenticatedProfileFollowingRouteImport } from './routes/_authenticated/profile.following'
import { Route as AuthenticatedProfileFollowersRouteImport } from './routes/_authenticated/profile.followers'
import { Route as AuthenticatedHashtagTagRouteImport } from './routes/_authenticated/hashtag.$tag'
import { Route as AuthenticatedConversationsIdRouteImport } from './routes/_authenticated/conversations.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUFixedIdRoute = AuthenticatedUFixedIdRouteImport.update({
  id: '/u/$fixedId',
  path: '/u/$fixedId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileSettingsRoute =
  AuthenticatedProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileFollowingRoute =
  AuthenticatedProfileFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileFollowersRoute =
  AuthenticatedProfileFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedHashtagTagRoute = AuthenticatedHashtagTagRouteImport.update({
  id: '/hashtag/$tag',
  path: '/hashtag/$tag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsIdRoute =
  AuthenticatedConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/hashtag/$tag': typeof AuthenticatedHashtagTagRoute
  '/profile/followers': typeof AuthenticatedProfileFollowersRoute
  '/profile/following': typeof AuthenticatedProfileFollowingRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/u/$fixedId': typeof AuthenticatedUFixedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/hashtag/$tag': typeof AuthenticatedHashtagTagRoute
  '/profile/followers': typeof AuthenticatedProfileFollowersRoute
  '/profile/following': typeof AuthenticatedProfileFollowingRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/u/$fixedId': typeof AuthenticatedUFixedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/conversations/$id': typeof AuthenticatedConversationsIdRoute
  '/_authenticated/hashtag/$tag': typeof AuthenticatedHashtagTagRoute
  '/_authenticated/profile/followers': typeof AuthenticatedProfileFollowersRoute
  '/_authenticated/profile/following': typeof AuthenticatedProfileFollowingRoute
  '/_authenticated/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/_authenticated/u/$fixedId': typeof AuthenticatedUFixedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conversations'
    | '/feed'
    | '/profile'
    | '/search'
    | '/conversations/$id'
    | '/hashtag/$tag'
    | '/profile/followers'
    | '/profile/following'
    | '/profile/settings'
    | '/u/$fixedId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conversations'
    | '/feed'
    | '/profile'
    | '/search'
    | '/conversations/$id'
    | '/hashtag/$tag'
    | '/profile/followers'
    | '/profile/following'
    | '/profile/settings'
    | '/u/$fixedId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conversations'
    | '/_authenticated/feed'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/conversations/$id'
    | '/_authenticated/hashtag/$tag'
    | '/_authenticated/profile/followers'
    | '/_authenticated/profile/following'
    | '/_authenticated/profile/settings'
    | '/_authenticated/u/$fixedId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$fixedId': {
      id: '/_authenticated/u/$fixedId'
      path: '/u/$fixedId'
      fullPath: '/u/$fixedId'
      preLoaderRoute: typeof AuthenticatedUFixedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings': {
      id: '/_authenticated/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AuthenticatedProfileSettingsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/following': {
      id: '/_authenticated/profile/following'
      path: '/following'
      fullPath: '/profile/following'
      preLoaderRoute: typeof AuthenticatedProfileFollowingRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/followers': {
      id: '/_authenticated/profile/followers'
      path: '/followers'
      fullPath: '/profile/followers'
      preLoaderRoute: typeof AuthenticatedProfileFollowersRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/hashtag/$tag': {
      id: '/_authenticated/hashtag/$tag'
      path: '/hashtag/$tag'
      fullPath: '/hashtag/$tag'
      preLoaderRoute: typeof AuthenticatedHashtagTagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations/$id': {
      id: '/_authenticated/conversations/$id'
      path: '/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof AuthenticatedConversationsIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
  }
}

interface AuthenticatedConversationsRouteChildren {
  AuthenticatedConversationsIdRoute: typeof AuthenticatedConversationsIdRoute
}

const AuthenticatedConversationsRouteChildren: AuthenticatedConversationsRouteChildren =
  {
    AuthenticatedConversationsIdRoute: AuthenticatedConversationsIdRoute,
  }

const AuthenticatedConversationsRouteWithChildren =
  AuthenticatedConversationsRoute._addFileChildren(
    AuthenticatedConversationsRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileFollowersRoute: typeof AuthenticatedProfileFollowersRoute
  AuthenticatedProfileFollowingRoute: typeof AuthenticatedProfileFollowingRoute
  AuthenticatedProfileSettingsRoute: typeof AuthenticatedProfileSettingsRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileFollowersRoute: AuthenticatedProfileFollowersRoute,
  AuthenticatedProfileFollowingRoute: AuthenticatedProfileFollowingRoute,
  AuthenticatedProfileSettingsRoute: AuthenticatedProfileSettingsRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedHashtagTagRoute: typeof AuthenticatedHashtagTagRoute
  AuthenticatedUFixedIdRoute: typeof AuthenticatedUFixedIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConversationsRoute: AuthenticatedConversationsRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedHashtagTagRoute: AuthenticatedHashtagTagRoute,
  AuthenticatedUFixedIdRoute: AuthenticatedUFixedIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
