REVOKE ALL ON FUNCTION public.add_group_member(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.can_view_user_content(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cleanup_reaction_notification() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cleanup_repost_notification() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_group_conversation(text, uuid[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_conversation(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_my_account() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_birth_date() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_or_create_direct_conversation(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_conversation_member(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.mark_conversation_read(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_on_comment() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_on_follow() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_on_reaction() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_on_repost() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_conversation_meta(uuid, text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.add_group_member(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_user_content(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_group_conversation(text, uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_conversation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_my_account() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_birth_date() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_or_create_direct_conversation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_conversation_member(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_conversation_read(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_conversation_meta(uuid, text, text) TO authenticated;

GRANT EXECUTE ON FUNCTION public.add_group_member(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.can_view_user_content(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_reaction_notification() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_repost_notification() TO service_role;
GRANT EXECUTE ON FUNCTION public.create_group_conversation(text, uuid[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_conversation(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_my_account() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_my_birth_date() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_or_create_direct_conversation(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_conversation_member(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_conversation_read(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_on_comment() TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_on_follow() TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_on_reaction() TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_on_repost() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_conversation_meta(uuid, text, text) TO service_role;